import React from "react";

// This is a static React version of the legacy shop layout from index-shop-backup.html
// Dynamic behaviors (cart, categories, etc) are not wired up here; this is for structure and static content reference.

export default function LegacyShopLayout() {
  return (
    <div>
      <header>
        <div className="logo">
          <img src="/assets/logo-48.png" srcSet="/assets/logo-96.png 2x" alt="Poster Point logo" className="site-logo" style={{width:48, height:48, display:'block'}} />
          <div>
            <div className="title blinking-text">Poster Point</div>
            <div className="subtitle">Anime posters • stickers • bookmarks</div>
          </div>
        </div>
        <button id="hamburger-btn" className="hamburger-btn" aria-label="Toggle categories" title="Toggle categories">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M3 7h18M3 12h18M3 17h18" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>
        </button>
        <button id="shop-type-btn" aria-label="Toggle shop type" title="Toggle shop type" style={{background:'transparent',border:'none',padding:8,cursor:'pointer',fontSize:18}}>🛍️</button>
        <div style={{flex:1}}></div>
        <div className="nav-actions" style={{display:'flex',gap:12,alignItems:'center'}}>
          <button id="theme-toggle" aria-label="Toggle theme" title="Toggle theme" style={{background:'transparent',border:'none',padding:8,cursor:'pointer',fontSize:18}}>🌙</button>
          <button id="nav-cart-btn" aria-label="Open cart" style={{padding:'8px 10px', display:'flex', alignItems:'center', gap:8, background:'white', border:'1px solid #ccc', borderRadius:8, cursor:'pointer', color:'#333', boxShadow:'0 1px 3px rgba(0,0,0,0.1)'}}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false"><path d="M3 3h2l.4 2M7 13h10l3-8H6.4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg>
            <span id="nav-cart-count" style={{fontWeight:700}}>0 items</span>
          </button>
        </div>
      </header>
      <div className="layout">
        <div id="sidebar-overlay" className="sidebar-overlay" aria-hidden="true"></div>
        <main className="main-content">
          <div className="toolbar">
            <div className="search">
              <input id="search-input" placeholder="Search posters, bookmarks, stickers..." />
            </div>
            <div id="offer-banner" style={{marginLeft:12, padding:'8px 12px', background:'linear-gradient(90deg,#fff,#f8f8f8)', borderRadius:8, fontWeight:700, color:'#2b7a2b', fontSize:13, display:'flex', alignItems:'center'}}>Buy 3 Get 1 Free • Buy 5 Get 2 Free • Buy 10 Get 5 Free</div>
            <div className="summary" id="toolbar-summary">Click a category to filter</div>
          </div>
          <p style={{color:'var(--muted)', marginTop:6, marginBottom:18}}>Click <strong>Buy now</strong> to collect items. Use the cart at bottom-right to checkout.</p>
          <section className="grid" id="product-grid">
            {/* product cards generated by JS */}
          </section>
        </main>
      </div>
      {/* Cart, Categories Panel, Shop Type Panel markup omitted for brevity. Add as needed. */}
    </div>
  );
}
